--- 
- name: 
  hosts: web_servers
  force_handlers: yes 
  tasks: 
  - name: 
    yum: 
      name: httpd
      state: installed 
  - name: 
    template: 
      src: index.html.j2 
      dest: /var/www/html/index.html
    notify: 
      - restart apache 

  - name: 
    service: 
      name: httpd 
      state: started
      enabled: true 
 
  handlers: 
    - name: restart apache 
      service:
        name: httpd
        state: restarted


