---
- name: 
  hosts: web_servers
  ignore_errors: yes 
  tasks: 
  - block:
      - name: block
        yum: 
          name: vsftpd
          state: present 
        #when: ansible_distribution == "Debian" 
    rescue: 
      - name: rescue 
        yum:
          name: wget
          state: present
    always: 
     - service: 
        name: vsftpd
        state: started
